output_root: "results"
site_list_file: "config/sites.txt"
job_titles:
  # VERY COMMON
  - "Data Analyst"
  - "Business Analyst"
  - "Business Systems Analyst"
  - "Business Data Analyst"
  - "Data Engineer"
  - "Data Scientist"
  - "Quality Assurance Engineer"
  - "AWS Engineer"
  - "AWS Cloud Engineer"
  - "Quality Business Analyst"
  - "EDI Analyst"
  - "Guidewire Developer"

keywords:
  - "apply"
  - "jobs"
  - "careers"

regions:
    - "United States"
    - "USA"

days_back: 1
chunk_size: 40

# NEW BLOCK → EXPLICIT JOB TYPE FILTER
job_type:
  modes: "contract,fulltime"

  include_keywords:
    contract:
      - "contract"
      - "contractor"
      - "c2c"
      - "w2"
      - "1099"
      - "contract position"

    fulltime:
      - "full time"
      - "fte"
      - "permanent"
      - "full-time"

    parttime:
      - "part time"

    temp:
      - "temporary"

    internship:
      - "internship"